backend:
  name: github
  repo: oxxecn-spec/MBORMC.github.io  # 你的 GitHub 用户名/仓库名
  branch: main
  base_url: https://mbormc123.oxxecn.workers.dev  # 你的网站地址
  auth_endpoint: /api/auth

media_folder: "images/uploads"   # 图片上传后的存放路径
public_folder: "/images/uploads"  # 图片在网页上的访问路径

collections:
  - name: "products"        # 产品集合
    label: "产品展示"        # 后台显示的标签
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "产品名称", name: "title", widget: "string" }
      - { label: "产品描述", name: "description", widget: "text" }
      - { label: "产品图片", name: "image", widget: "image" }
