backend:
  name: github
  repo: oxxecn-spec/MBORMC.github.io
  branch: main
  base_url: https://mbormc--github-io.pages.dev
  auth_endpoint: /api/auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "产品展示"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "产品名称", name: "title", widget: "string" }
      - { label: "产品描述", name: "description", widget: "text" }
      - { label: "产品图片", name: "image", widget: "image" }
